export const TOOL_LIST_REQUEST = "TOOL_LIST_REQUEST";
export const TOOL_LIST_SUCCESS = "TOOL_LIST_SUCCESS";
export const TOOL_LIST_FAIL = "TOOL_LIST_FAIL";

export const TOOL_DETAILS_REQUEST = "TOOL_DETAILS_REQUEST";
export const TOOL_DETAILS_SUCCESS = "TOOL_DETAILS_SUCCESS";
export const TOOL_DETAILS_FAIL = "TOOL_DETAILS_FAIL";

export const TOOL_DELETE_REQUEST = "TOOL_DELETE_REQUEST";
export const TOOL_DELETE_SUCCESS = "TOOL_DELETE_SUCCESS";
export const TOOL_DELETE_FAIL = "TOOL_DELETE_FAIL";

export const TOOL_CREATE_REQUEST = "TOOL_CREATE_REQUEST";
export const TOOL_CREATE_SUCCESS = "TOOL_CREATE_SUCCESS";
export const TOOL_CREATE_FAIL = "TOOL_CREATE_FAIL";
export const TOOL_CREATE_RESET = "TOOL_CREATE_RESET";

export const TOOL_UPDATE_REQUEST = "TOOL_UPDATE_REQUEST";
export const TOOL_UPDATE_SUCCESS = "TOOL_UPDATE_SUCCESS";
export const TOOL_UPDATE_FAIL = "TOOL_UPDATE_FAIL";
export const TOOL_UPDATE_RESET = "TOOL_UPDATE_RESET";

export const TOOL_REVIEW_CREATE_REQUEST = "TOOL_REVIEW_CREATE_REQUEST";
export const TOOL_REVIEW_CREATE_SUCCESS = "TOOL_REVIEW_CREATE_SUCCESS";
export const TOOL_REVIEW_CREATE_FAIL = "TOOL_REVIEW_CREATE_FAIL";
export const TOOL_REVIEW_CREATE_RESET = "TOOL_REVIEW_CREATE_RESET";
